version: '2'

services:
  php:
    image: supermp/php
    volumes:
      - app:/var/www/html

  nginx:
    image: supermp/nginx
    ports:
      - 80:80
    volumes:
      - app:/var/www/html
    environment:
      WEB_ROOT: public

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  redis:
    image: redis:3.2
    ports:
      - 6379:6379
    volumes:
      - redis:/data

volumes:
  app:
  mysql:
  redis:
